version: "3"
services:
  api-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: api-api
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
  da-vue-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: da-vue-client
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
